### ISSUE TITLE
Very outdated openssl version in static murmur build

### ISSUE THREAD

**Issue by toby63** [PHLAK/docker-mumble#16]
As reported by user @tylerszabo on upstream mumble the openssl version in the static murmur build is very outdated, it's from 2017(!), see:
https://github.com/mumble-voip/mumble/issues/4001#issuecomment-696499188

You might argue that this is an upstream problem, but the Mumble Team is refusing to change it, see:
https://github.com/mumble-voip/mumble/issues/4001#issuecomment-696519165

So in the best interest of your users, could you rewrite your dockerfile to use the murmur package from the alpine repo?
This will use alpines openssl version, which is recent.

Edit: Sorry for the confusion with the names, I somehow misread things twice...

**Comment by tylerszabo** [comment]
Just to note - the `murmurd` in Alpine version `3.12` is still only the `1.3.1` build and not `1.3.2` and there have been a few fixes to `murmurd` since then from the looks of the commit history. So it might not be a drop-in replacement.

With that said, the Dockerfile can become pretty trivial. I'm currently using the following:

```Dockerfile
FROM alpine:3.12

ENV MURMUR_INI=/etc/murmur.ini

RUN apk add murmur

EXPOSE 64738/tcp 64738/udp 50051

USER murmur:murmur
CMD /usr/bin/murmurd -v -fg -ini $MURMUR_INI
```

**Comment by toby63** [comment]
@PHLAK As you downvoted my [comment](https://github.com/mumble-voip/mumble/issues/4001#issuecomment-697472613) on the mumble issue, why don't you want to use this easy alternative that @tylerszabo has outlined?

I don't see a problem.
The mumble team will find a solution for 1.4 release (whenever that release might be).

**Comment by PHLAK** [comment]
Thanks for bringing up the issue, however I will not be transitioning over to murmur from the alpine repo. This image has always intended to be directly from-the-source and as @tylerszabo pointed out it's not the latest version.

> the Mumble Team is refusing to change it

According to @Kissaki [in the upstream issue](https://github.com/mumble-voip/mumble/issues/4001#issuecomment-696865465) it sounds like they're planning on addressing this with v1.4

> 1.4 will have updated environments and stuff, including static server build. We are focusing on moving that forward.

@toby63 I down voted your issue because your suggestion to "simply take it down until there is a recent version" is unreasonable.

Also, as far as I can tell everything still works despite the outdated OpenSSL version.

<p align="center">
  <img src="https://user-images.githubusercontent.com/53531/94168562-9d628e80-fe42-11ea-9104-2dee036a086b.png" alt="Screenshot 2020-09-24 08:39:05" width="50%;">
 
  <img src="https://user-images.githubusercontent.com/53531/94168572-9fc4e880-fe42-11ea-9a3e-d548f3aa9243.png" alt="Screenshot 2020-09-24 08:39:21" width="50%;">
</p>

I understand there is potential security risk involved here and hope the Mumble developers get this updated with the new version ASAP.

**Comment by toby63** [comment]
I completely disagree, but at least be fair and tell your users that your Dockerfile contains a super-old encryption library, not everyone wants something like that.

Irresponsible behaviour everywhere, no wonder we have a steady IT-security crisis.
